# Generated by Django 4.1.1 on 2023-01-31 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0006_remove_bill_bnumber_alter_bill_bpname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='test_name',
            new_name='testn',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='test_id',
        ),
        migrations.AddField(
            model_name='bill',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='labapp.tests'),
            preserve_default=False,
        ),
    ]
