# Generated by Django 4.1.1 on 2023-02-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0007_rename_test_name_bill_testn_remove_bill_test_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testname',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
