# Generated by Django 4.1.1 on 2023-02-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0008_testname_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bnumber',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='dname',
            field=models.CharField(default='A', max_length=100),
            preserve_default=False,
        ),
    ]
