# Generated by Django 4.1.1 on 2023-02-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0009_bill_bnumber_bill_dname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
