# Generated by Django 4.1.1 on 2023-02-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0010_bill_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testname',
            name='price',
        ),
    ]
