# Generated by Django 4.1.1 on 2023-02-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0012_testname_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
