# Generated by Django 4.1.1 on 2023-02-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0013_patient_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='barcode',
        ),
        migrations.AddField(
            model_name='bill',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
