# Generated by Django 4.1.1 on 2023-02-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0014_remove_patient_barcode_bill_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
