# Generated by Django 4.1.1 on 2023-02-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0020_alter_bill_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='testn',
        ),
    ]
