# Generated by Django 4.1.1 on 2023-02-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0021_remove_bill_testn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='testn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='labapp.testname'),
            preserve_default=False,
        ),
    ]
