# Generated by Django 4.1.1 on 2023-02-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0023_remove_bill_testn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bpname',
        ),
    ]
