# Generated by Django 4.1.1 on 2023-02-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0025_remove_bill_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bpname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
