# Generated by Django 4.1.1 on 2023-02-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0028_remove_bill_bnumber_remove_bill_dname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='test_name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='tid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
