# Generated by Django 4.1.1 on 2023-02-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0029_bill_pname_bill_test_name_bill_tid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='tid',
            new_name='pid',
        ),
    ]
