# Generated by Django 4.1.1 on 2023-02-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0031_bill_dname_bill_email_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='tid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
