# Generated by Django 4.1.1 on 2023-03-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0033_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
