# Generated by Django 4.1.1 on 2023-03-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0035_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
